# SPDX-FileCopyrightText: 2020 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

[tool.black]
line-length = 79

[tool.ruff]
extend-select = ["C90", "D", "I"]
line-length = 79

[tool.ruff.pydocstyle]
convention = "google"
